# Generated by Django 2.2.11 on 2020-03-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ('created_at',)},
        ),
    ]
