# Generated by Django 2.2.11 on 2020-03-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20200322_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoken',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',)},
        ),
    ]
