# Generated by Django 3.1 on 2020-11-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_auto_20200322_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'get_latest_by': 'played_at', 'ordering': ('-played_at',)},
        ),
        migrations.AddField(
            model_name='track',
            name='data',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
