# Generated by Django 3.1 on 2020-11-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_auto_20201102_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='track',
            name='duration_ms',
        ),
        migrations.RemoveField(
            model_name='track',
            name='track_number',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
