# Generated by Django 3.1 on 2020-11-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_auto_20201102_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'get_latest_by': 'last_played_at', 'ordering': ('-last_played_at',)},
        ),
        migrations.RenameField(
            model_name='track',
            old_name='played_at',
            new_name='last_played_at',
        ),
    ]
