# Generated by Django 3.1 on 2020-11-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_auto_20201102_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
