# Generated by Django 3.1 on 2020-11-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0012_auto_20201104_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
        migrations.RemoveField(
            model_name='track',
            name='last_played_at',
        ),
    ]
