# Generated by Django 3.1 on 2020-11-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0013_auto_20201104_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
